#!/usr/bin/env python
# encoding: utf-8

name = "Furfuryl_OH"
shortDesc = "Ab initio kinetics of OH-initiated reactions of 2-furfuryl alcohol, 2023"
longDesc = """
DOI: 10.1016/j.fuel.2022.127325
"""
autoGenerated=False
entry(
    index = 0,
    label = "2FFOH + OH <=> P1 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.0512361,'cm^3/(mol*s)'), n=3.87161, Ea=(16.6539,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 1.94442, dn = +|- 0.0848332, dEa = +|- 0.529245 kJ/mol"""),
)

entry(
    index = 1,
    label = "2FFOH + OH <=> P2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.78475,'cm^3/(mol*s)'), n=3.62002, Ea=(21.3331,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 1.95194, dn = +|- 0.0853261, dEa = +|- 0.532321 kJ/mol"""),
)

entry(
    index = 2,
    label = "2FFOH + OH <=> P3 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.74552,'cm^3/(mol*s)'), n=3.72969, Ea=(24.3885,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 2.07331, dn = +|- 0.0930216, dEa = +|- 0.58033 kJ/mol"""),
)

entry(
    index = 3,
    label = "2FFOH + OH <=> P4 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(220.12,'cm^3/(mol*s)'), n=2.98141, Ea=(-9.36757,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 1.08693, dn = +|- 0.0106341, dEa = +|- 0.0663422 kJ/mol"""),
)

entry(
    index = 4,
    label = "INT1 <=> P5 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.32191e+21,'s^-1'), n=-1.78223, Ea=(135.819,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 1.22401, dn = +|- 0.0257873, dEa = +|- 0.160878 kJ/mol"""),
)

entry(
    index = 5,
    label = "INT9 <=> P12 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.62491e+23,'s^-1'), n=-1.87579, Ea=(121.11,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 1.16357, dn = +|- 0.0193264, dEa = +|- 0.120571 kJ/mol"""),
)

entry(
    index = 6,
    label = "INT25 <=> P39 + CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.48086e+12,'s^-1'), n=0.24754, Ea=(35.88,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 1.0486, dn = +|- 0.00605391, dEa = +|- 0.0377683 kJ/mol"""),
)

entry(
    index = 7,
    label = "INT26 <=> P40 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.05549e+11,'s^-1'), n=0.878136, Ea=(67.5505,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 24 data points; dA = *|/ 1.68137, dn = +|- 0.0662896, dEa = +|- 0.413558 kJ/mol"""),
)

